# Generated by Django 4.1.7 on 2023-07-24 13:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('capstone', '0007_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pub',
            name='users_visited',
            field=models.ManyToManyField(blank=True, related_name='visited_pubs', to=settings.AUTH_USER_MODEL),
        ),
    ]
