# Generated by Django 4.1.7 on 2023-05-12 11:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_like_id_alter_post_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='following_users', related_query_name='followed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
