# Generated by Django 4.1.7 on 2023-06-12 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=280)),
                ('date_visited', models.DateTimeField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TEST_Pub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('heritage_stars', models.IntegerField()),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('photos', models.ImageField(blank=True, upload_to='pub_photos')),
                ('open', models.BooleanField(default=True)),
                ('listed', models.CharField(blank=True, max_length=100)),
                ('posts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TEST_pub_posts', to='capstone.post')),
                ('users_visited', models.ManyToManyField(related_name='TEST_visited_pubs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'test_pub',
            },
        ),
        migrations.CreateModel(
            name='TEST_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=280)),
                ('date_visited', models.DateTimeField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('heritage_stars', models.IntegerField(default=0)),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('photos', models.ImageField(blank=True, upload_to='pub_photos')),
                ('open', models.BooleanField(default=True)),
                ('listed', models.CharField(blank=True, max_length=100)),
                ('posts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pub_posts', to='capstone.post')),
                ('users_visited', models.ManyToManyField(related_name='visited_pubs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
