# Generated by Django 4.1.7 on 2023-06-12 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pub',
            old_name='heritage_stars',
            new_name='inventory_stars',
        ),
        migrations.RenameField(
            model_name='test_pub',
            old_name='heritage_stars',
            new_name='inventory_stars',
        ),
    ]
