# Generated by Django 4.1.7 on 2023-06-27 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0002_alter_pub_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_pub',
            name='posts',
        ),
        migrations.RemoveField(
            model_name='test_pub',
            name='users_visited',
        ),
        migrations.RemoveField(
            model_name='pub',
            name='posts',
        ),
        migrations.AddField(
            model_name='post',
            name='pub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pub_posts', to='capstone.pub'),
        ),
        migrations.DeleteModel(
            name='TEST_Post',
        ),
        migrations.DeleteModel(
            name='TEST_Pub',
        ),
    ]
