# Generated by Django 4.1.7 on 2023-06-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0002_rename_heritage_stars_pub_inventory_stars_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pub',
            name='inventory_stars',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='test_pub',
            name='inventory_stars',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
