# Generated by Django 4.1.7 on 2023-06-12 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0003_alter_pub_inventory_stars_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_pub',
            name='posts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TEST_pub_posts', to='capstone.post'),
        ),
    ]
