# Generated by Django 4.1.7 on 2023-06-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0004_alter_test_pub_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_pub',
            name='inventory_stars',
            field=models.IntegerField(default=0),
        ),
    ]
