# Generated by Django 4.1.7 on 2023-07-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0005_rename_pub_id_pub_custom_pub_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pub',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pub',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
