# Generated by Django 4.1.7 on 2023-06-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0005_alter_test_pub_inventory_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_pub',
            name='inventory_stars',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
